export const PETAINT_PERSONAL_DETAILS = "PETAINT_PERSONAL_DETAILS";
export const PETAINT_INSURANCE_DETAILS = "PETAINT_INSURANCE_DETAILS";
export const PETAINT_FAMILY_MEMBER_DETAILS = "PETAINT_FAMILY_MEMBER_DETAILS";
